//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ILetsGoBikingService")]
    public interface ILetsGoBikingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGoBikingService/GetItinerary", ReplyAction="http://tempuri.org/ILetsGoBikingService/GetItineraryResponse")]
        string GetItinerary(string origin, string destination);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILetsGoBikingService/GetItinerary", ReplyAction="http://tempuri.org/ILetsGoBikingService/GetItineraryResponse")]
        System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILetsGoBikingServiceChannel : TestClient.ServiceReference1.ILetsGoBikingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LetsGoBikingServiceClient : System.ServiceModel.ClientBase<TestClient.ServiceReference1.ILetsGoBikingService>, TestClient.ServiceReference1.ILetsGoBikingService {
        
        public LetsGoBikingServiceClient() {
        }
        
        public LetsGoBikingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LetsGoBikingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetsGoBikingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LetsGoBikingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetItinerary(string origin, string destination) {
            return base.Channel.GetItinerary(origin, destination);
        }
        
        public System.Threading.Tasks.Task<string> GetItineraryAsync(string origin, string destination) {
            return base.Channel.GetItineraryAsync(origin, destination);
        }
    }
}
